require('./plugin/pace/pace-theme-minimal.css')
require('./plugin/bootstrap/css/bootstrap.min.css')
require('./plugin/toastr/toastr.min.css')
require('./plugin/bootstrap/js/bootstrap.min.js')
require('./plugin/pace/pace.min.js')